version: '3.8'
services:
   web:
       build: .
       command: python manage.py runserver 0.0.0.0:8000
       volumes:
           - ./media:/media
           - ./db.sqlite3:/db.sqlite3
       ports:
           - 8000:8000
